# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: sawtelle
email: your-email@domain.com
author: Your Name
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: "Copyright &copy; 2021 SAWTELLE LLC. All Rights Reserved."
credits: 'design credits: <a href="https://github.com/swcool/landing-page-theme">github.com/swcool</a>.'
disclaimer: "*DISCLAIMER Services (APIs) provided by SAWTELLE LLC are intended for research and development purposes, and are not designed nor approved for clinical diagnostic use. Sawtelle LLC is not liable for any consequential damages that result from the use of these services."
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/sawtellellc
  - title: twitter
    url: https://twitter.com/sawtellellc
  - title: info-circle
    url: https://sawtellellc.square.site
  #- title: youtube
  #  url: https://www.youtube.com/channel/UCuiTlP-4N47VszfT5kHeGpQ/featured