# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://sawtellellc.github.io/
title: sawtelle
email: ""
author: sawtelle
description: > # "Write an awesome description for your new site here. 
  Creating scalable, easy to use, machine learning & computer vision solutions one API call at time.
copyright: "Copyright &copy; 2021 SAWTELLE LLC. All Rights Reserved."
credits: 'design credits: <a href="https://github.com/swcool/landing-page-theme">github.com/swcool</a>.'
disclaimer: "*CAUTION -- For Investigational Use Only. The performance characteristics of this product have not been established. Sawtelle LLC is not liable for any consequential damages that result from the use of these services."
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    icon: github
    url: https://github.com/sawtellellc
  - title: twitter
    icon: twitter
    url: https://twitter.com/sawtellellc
  - title: consulting
    icon: info-circle
    url: https://sawtellellc.square.site
  #- title: youtube
  #  url: https://www.youtube.com/channel/UCuiTlP-4N47VszfT5kHeGpQ/featured
